Repository ros2/ci, pull requests merged in 2018-05, with the labels that each got.

#161 Create a test job matching each ci job.
  create_jenkins_job.py
Labels: in review

#164 Stop shipping OpenCV libraries in packaging artifact
  ros2_batch_job/packaging.py
Labels: in review

#167 display console output directly for the bridge
  ros2_batch_job/packaging.py
Labels: in review

#165 create manually triggered coverage jobs
  create_jenkins_job.py
Labels: in review

#169 stop building tests on packaging jobs
  ros2_batch_job/packaging.py
Labels: in progress

#170 allow packaging jobs to run in parallel?
  job_templates/packaging_job.xml.em
Labels: in review, question

#166 pass --no-warn-unused-cli to CMake to avoid unwanted warnings
  ros2_batch_job/__main__.py
  ros2_batch_job/packaging.py
Labels: in review

#171 don't try bridge on MacOS
  job_templates/packaging_job.xml.em
Labels: in review

#174 Install catkin if we need to source ROS1
  linux_docker_resources/Dockerfile
Labels: in review

#172 fix typo in tb2 dependencies: libusb-1.0.0-dev -> libusb-1.0-0-dev
  linux_docker_resources/Dockerfile
Labels: in review

#175 add parameter to choose colcon version/branch
  job_templates/ci_job.xml.em
  job_templates/packaging_job.xml.em
  job_templates/snippet/property_parameter-definition_common.xml.em
  ros2_batch_job/__main__.py
Labels: enhancement, in review

#177 add pattern to match pytest.xml result files
  job_templates/snippet/publisher_xunit.xml.em
Labels: bug, in review
