Repository ros2/ci, pull requests merged in 2018-06, with the labels that each got.

#179 skip Pytests with a linter marker in repeated jobs
  create_jenkins_job.py
Labels: enhancement, in review

#168 remove trailing forward slash in default jenkins url
  create_jenkins_job.py
Labels: in review

#180 blacklist vision_opencv packages we dont use on CI
  ros2_batch_job/__main__.py
Labels: in review

#181 readd option to use Debian pkg of Connext
  create_jenkins_job.py
  job_templates/ci_job.xml.em
  job_templates/ci_launcher_job.xml.em
  job_templates/snippet/property_parameter-definition.xml.em
  linux_docker_resources/Dockerfile
  linux_docker_resources/entry_point.sh
  ros2_batch_job/__main__.py
  ros2_batch_job/linux_batch/__init__.py
Labels: in review

#183 remove special escaping for nested arguments
  create_jenkins_job.py
  ros2_batch_job/__main__.py
  ros2_batch_job/packaging.py
Labels: in review

#184 Quote C / CXX flags
  ros2_batch_job/__main__.py
Labels: in review

#148 Migrate CI to bionic
  create_jenkins_job.py
  job_templates/ci_job.xml.em
  job_templates/ci_launcher_job.xml.em
  job_templates/packaging_job.xml.em
  job_templates/snippet/property_parameter-definition.xml.em
  job_templates/snippet/property_parameter-definition_common.xml.em
  linux_docker_resources/Dockerfile
  linux_docker_resources/entry_point.sh
Labels: in review

#188 Keep producing xenial artifacts?
  create_jenkins_job.py
Labels: in review, question

#186 fix empy code indentation for readibility
  job_templates/ci_job.xml.em
  job_templates/ci_launcher_job.xml.em
  job_templates/packaging_job.xml.em
Labels: in review

#185 install libassimp-dev for rviz
  linux_docker_resources/Dockerfile
Labels: in review

#189 Support packaging job on xenial
  job_templates/packaging_job.xml.em
Labels: in review

#191 Install connext conditionally
  job_templates/ci_job.xml.em
  linux_docker_resources/Dockerfile
Labels: in review

#194 Replace today_str as part of packaging jobs too
  job_templates/packaging_job.xml.em
Labels: in review

#192 Support Connext in packaging jobs, package all rmw impls by default
  create_jenkins_job.py
  job_templates/packaging_job.xml.em
  job_templates/snippet/property_parameter-definition.xml.em
  job_templates/snippet/property_parameter-definition_rmw_implementations.xml.em
Labels: in review

#196 rename build-base to test-result-base
  ros2_batch_job/__main__.py
  ros2_batch_job/packaging.py
Labels: in review

#197 Add ubuntu distro to linux packaging description
  job_templates/packaging_job.xml.em
Labels: in review

#198 blacklist some package for Windows packaging
  ros2_batch_job/__main__.py
Labels: enhancement, in review
