Repository ros2/ci, pull requests merged in 2019-08, with the labels that each got.

#324 Revert "pin version of pydocstyle to 3.0.0 (was 4.0.0)"
  ros2_batch_job/__main__.py
Labels: in review

#325 install Python package mypy
  linux_docker_resources/Dockerfile
  ros2_batch_job/__main__.py
Labels: in review

#323 kill existing colcon when stating CI on Windows to avoid file locks
  ros2_batch_job/__main__.py
Labels: in review

#326 Run update-ccache-symlinks after build-essential is installed.
  linux_docker_resources/Dockerfile
Labels: in review

#327 install CycloneDDS dependencies
  linux_docker_resources/Dockerfile
Labels: enhancement, in review

#314 Adjust CentOS builds for recently stable updates
  linux_docker_resources/Dockerfile-CentOS
Labels: in review

#328 Update Dockerfile to support Xenial again
  linux_docker_resources/Dockerfile
Labels: in review

#331 Initialize the D-Bus Machine ID GUID
  linux_docker_resources/Dockerfile-CentOS
Labels: bug

#332 Use single quotes in test args
  create_jenkins_job.py
Labels: bug, in review
