Repository ros2/ci, pull requests merged in 2019-04, with the labels that each got.

#271 force reinstallation of numpy
  ros2_batch_job/__main__.py
Labels: bug, in review

#270 Add CentOS jobs
  create_jenkins_job.py
  job_templates/ci_job.xml.em
  job_templates/packaging_job.xml.em
  job_templates/snippet/publisher_warnings.xml.em
  linux_docker_resources/Dockerfile-CentOS
Labels: enhancement, in review

#272 install custom wheel of numpy for Windows debug
  ros2_batch_job/__main__.py
Labels: bug, in review

#273 bump OpenSplice version to 6.9.190304
  linux_docker_resources/Dockerfile
Labels: in review

#274 use debug Python wheels in packaging job
  job_templates/packaging_job.xml.em
  ros2_batch_job/__main__.py
Labels: bug, in review

#275 Modify test_args_default instead of overriding it
  create_jenkins_job.py
Labels: bug, in review

#277 skip qt_gui_cpp from coverage job
  create_jenkins_job.py
Labels: in review

#278 Discard old CI builds.
  create_jenkins_job.py
  job_templates/ci_job.xml.em
  job_templates/snippet/property_build-discard.xml.em
Labels: in review

#276 use Visual Studio 2019
  job_templates/ci_job.xml.em
  job_templates/ci_launcher_job.xml.em
  job_templates/packaging_job.xml.em
  job_templates/snippet/property_parameter-definition.xml.em
  job_templates/snippet/property_parameter-definition_common.xml.em
  ros2_batch_job/__main__.py
  ros2_batch_job/windows_batch/__init__.py
Labels: enhancement, in review

#280 Use ==/!= to compare str, bytes, and int literals
  ros2_batch_job/__main__.py
Labels: in review

#281 Adjust Dockerfile-CentOS based on recent upstream work
  linux_docker_resources/Dockerfile-CentOS
Labels: in review

#282 Skip image_tools on CentOS due to OpenCV 3 requirement
  create_jenkins_job.py
Labels: in review

#279 Modify ASAN/TSAN nightly jobs configuration
  create_jenkins_job.py
Labels: in progress

#283 Set default retention to 1000 days, 3000 builds.
  create_jenkins_job.py
Labels: in review

#285 Add build discard template to packaging jobs.
  job_templates/packaging_job.xml.em
Labels: in progress

#286 Only run tests on rcutils for the TSA nightly
  create_jenkins_job.py
Labels: in progress

#284 Disable OSRF memory testing tool in TSAN job
  create_jenkins_job.py
Labels: in progress
