Repository ros2/ci, pull requests merged in 2019-06, with the labels that each got.

#302 Fix the CentOS jobs
  create_jenkins_job.py
  linux_docker_resources/Dockerfile-CentOS
Labels: in review

#301 Blacklist rqt_py_common on Windows debug builds.
  ros2_batch_job/__main__.py
Labels: in review

#249 Post rosbridge pkgs
  create_jenkins_job.py
  job_templates/packaging_job.xml.em
  ros2_batch_job/__main__.py
  ros2_batch_job/packaging.py
Labels: in progress

#299 Fix armhf build support
  create_jenkins_job.py
  job_templates/ci_job.xml.em
  job_templates/packaging_job.xml.em
  linux_docker_resources/Dockerfile
Labels: in review

#305 Suppress gcc-7.x ABI incompatibility notes
  create_jenkins_job.py
Labels: in review

#307 Fix armhf packaging support
  job_templates/packaging_job.xml.em
  ros2_batch_job/packaging.py
Labels: bug, in review

#309 Fix OSX package names
  ros2_batch_job/packaging.py
Labels: bug, in review
