Repository ros2/ci, pull requests merged in 2019-03, with the labels that each got.

#253 use `VER>NUL` instead of `true` on windows
  ros2_batch_job/__main__.py
Labels: in review

#251 use OpenSplice 6.9.190227 on Linux
  linux_docker_resources/Dockerfile
Labels: in review

#255 remove nightly Xenial jobs
  create_jenkins_job.py
Labels: bug, in review

#256 disable turtlebot jobs
  create_jenkins_job.py
  job_templates/ci_job.xml.em
Labels: bug, in review

#258 Install lxml debug build when relevant on Windows
  ros2_batch_job/__main__.py
Labels: in review

#259 Make Windows packaging job use the release version of LXML
  ros2_batch_job/__main__.py
Labels: in review

#260 Update opensplice package version.
  linux_docker_resources/Dockerfile
Labels: in review

#261 Force LXML to be reinstalled on Windows
  ros2_batch_job/__main__.py
Labels: in review

#254 Add thread sanitizer nightly job for linux
  create_jenkins_job.py
Labels: in review

#262 skip testing rviz packages on aarch64 repeated since they are known to be flaky
  create_jenkins_job.py
Labels: in review

#263 Add Amazon team to recipients for builds they want.
  create_jenkins_job.py
Labels: in progress

#257 Install libc++ development libraries when building with clang.
  linux_docker_resources/Dockerfile
Labels: in review

#252 Fix parameter name in printout.
  job_templates/ci_job.xml.em
Labels: in review

#266 Reduce scope of tsan job to stay below memory limitations.
  create_jenkins_job.py
Labels: in review

#264 Set the nightly clang build to run the libcxx mixin
  create_jenkins_job.py
Labels: in review

#267 Add nightly job running Address Sanitizer.
  create_jenkins_job.py
Labels: in review

#268 install numpy
  linux_docker_resources/Dockerfile
  ros2_batch_job/__main__.py
Labels: enhancement, in review

#243 Revert temporary hack to keep logs on Windows
  job_templates/ci_job.xml.em
  ros2_batch_job/__main__.py
Labels: in progress

#269 use latest release 0.7 of lark-parser
  ros2_batch_job/__main__.py
Labels: in review
